name: cppcheck-action
on: [push]
jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install cppcheck
        run: sudo apt-get -y install cppcheck
      - name: Cppcheck 
        run: cppcheck 3_Implementation
Â© 2022 GitHub, Inc.
Terms
Privacy

